language: java
jdk:
- oraclejdk8
sudo: false
before_deploy: mvn package
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id:
    secure: FzsWbjsbDEel0IZeN/S792hYZ35udW5//8N8evbhdJ8P4cmI7Io7O2OHP20vNYaFyuvT3p0V16eQFxMVXqodgMSGuYamaEaDZm2RWSjbDS0satqlUau8DPX5AE787o7vVAspL5avTi+zIE3UIE4d3C24gzobu8BEnHg5DBiDMwZP/MmqluNdxeWglH1DJ4j2G5LXpKB/T2k1jdgT6gjiEZ9aARNW2EOptObuEP+to9ST7Qp6BpPKGUItVzzOxtJ2PfKas57mBihSpVdLTa6FhRL0IDdsUJwuIrDtMTXkiEbw4enz0DX6sjpMjNKTKPS8xQBc2vjXIC4o6QOEqs4vuFvz0eF/m5AXbtnQ6GhDxS0AP+aVAEg3CQn2u1o1PdPQUVSOAKpvmnc4nenBLIpzJE+4uwkrWu+J13N48LODiT6xqtVlbRYD3AbaBKAtxAesJgGagpkE7O1uUbErFTmaSOz7KBA3HbQ57KWpy7yQ1SexO5gb8aTD2h128S4q8mDv7ghIkPNloqQ+Rgs+P+B7BGMVu7WGVA34OXLJKM/9TSS2EZgeCyAeD8E7BRBs0+bHDYUqpvwhXO/dRLOtKxYQpIOJGH8XbV6V2eSLN6oDTXHUr752XYe5LugXGjUGbLQbhkEwFS5BCLJMMWBYVmkfHNIN1HZPXO1Uv1wzU2yH4ls=
  secret_access_key:
    secure: aTELhr984wvZkiecP2kZiQ3mk3w6PAK3bwzROLLN104ymes2N4F6q5tmIFehpP8AXRSkt4XFdFF+M7F1TthCHxShftV1EDTuNBZFVWzOfz2j3qdieD/yFN51KLANbCyMZCY2+Duu3w2zDMgn5/0wb5tqivxgCWz5VltoyVZZPuO8EWd8PQ+sXQkfn/f9dWEO6fojl8BWsJEqttu9WUhW0kwuNgR6DQbDGFSgW/ffFtQiIYpvQYXuZ7fWeyvRQYsy5TQ+HNljT+GorOGlTCsQ7cTAeKdCJgOwGBpc7epHoOehE9z935EIk+UKKjezBXeUJD+KuwWK3AFDW4A0sci5ZcvSyznvrRnTgg7KYjDIwz3HX8tq68CTVdoXe/m0nKbe/7LsT7IOfaclwy3K19QhCoTCd9o5PMFPceK4EiuaDgQXZVHavt6ghbkKPiUWT7idMzN7RyFuq06bkueH3+CL6LzjbK8d58DiIa6OJQ9P6CKJNVfWWKzVzHhd/ATtfy1E1MRbhLJdSiqc9+45g2lqSNnt6Htfo5GAyK+nN105/jCZQI44ZWByjELxJvWPF28vu++/gWkCx1U2KNx0D/1atcY+a+JhdukkGQkC1pJqz7vlsPTFkmlBGXt+/wRg3PNKcn9fGiJLerJnlrxCbIjYil15pgFapAhvInfbgzQUGyM=
  region: us-east-1
  app: BridgeUserDataDownloadService
  env:
    develop: Bridge-UDD-prod
  bucket_name: elasticbeanstalk-us-east-1-649232250620
  zip-file: target/BridgeUserDataDownloadService-1.0.war
